version: '2'

services:
   db:
     image: mysql:5.7
     volumes:
       - db_data:/var/lib/mysql
     restart: always
     networks:
       - proxy
     environment:
       MYSQL_ROOT_PASSWORD: ${CLIENT_ID}
       MYSQL_DATABASE: wordpress
       MYSQL_USER: wordpress
       MYSQL_PASSWORD: wordpress

   wordpress:
     image: wordpress:latest
     restart: always
     environment:
       WORDPRESS_DB_HOST: db:3306
       WORDPRESS_DB_USER: wordpress
       WORDPRESS_DB_PASSWORD: wordpress
     networks:
       - proxy
     labels:
       - "traefik.enable=true"
       - "traefik.http.routers.wordpress.entrypoints=http"
       - "traefik.http.routers.wordpress.rule=Host(`wordpress.mercatum.fr`)"
       - "traefik.http.middlewares.wordpress-https-redirect.redirectscheme.scheme=https"
       - "traefik.http.routers.wordpress.middlewares=wordpress-https-redirect"
       - "traefik.http.routers.wordpress-secure.entrypoints=https"
       - "traefik.http.routers.wordpress-secure.rule=Host(`wordpress.mercatum.fr`)"
       - "traefik.http.routers.wordpress-secure.tls=true"
       - "traefik.http.routers.wordpress-secure.tls.certresolver=http"

volumes:
    db_data:

networks:
  proxy:
    external: true
